"""Base class for trading strategies.

Classes
-------
StrategyType
    The types of trading strategy.
Strategy
    Base class from which every trading strategy inherits.
"""

import importlib
import traceback
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Tuple

from pandas import DataFrame as df

from liualgotrader.common import config
from liualgotrader.common.data_loader import DataLoader  # type: ignore
from liualgotrader.common.tlog import tlog
from liualgotrader.models.accounts import Accounts
from liualgotrader.models.algo_run import AlgoRun
from liualgotrader.models.keystore import KeyStore
from liualgotrader.trading.base import Trader


class StrategyType(Enum):
    """Enumeration of trading strategy types: day trade or swing."""

    DAY_TRADE = 1
    SWING = 2


class Strategy(object):
    """Base class from which every trading strategy must inherit.

    Subclasses override run, or should_run_all and run_all, to make trading
    decisions.

    Attributes
    ----------
    name: str
        The strategy name, as used in the trade plan.
    type: StrategyType
        The strategy type.
    batch_id: str
        The identifier that groups the executions of a batch.
    ref_run_id: int
        The reference run identifier, used in backtesting, or None.
    algo_run
        The record of this strategy run.
    schedule: List[Dict]
        The execution windows defined in the trade plan.
    data_loader: DataLoader
        The loader used to access symbol data, or None.
    support_fractional: bool
        Whether the strategy trades fractional quantities.
    account_id
        The identifier of the strategy's account, or None.
    global_var: Dict
        The cached values of the shared key store.

    Methods
    -------
    calc_qty
        Return the quantity the account balance can buy at a price.
    create
        Save the strategy run and return whether it should execute.
    should_run_all
        Return whether the framework uses run_all or run.
    run_all
        Return trading actions for all symbols at once.
    run
        Return the trading action for a single symbol.
    is_sell_time
        Return whether the strategy may sell at a given time.
    is_buy_time
        Return whether the strategy may buy at a given time.
    buy_callback
        Handle a successful buy.
    sell_callback
        Handle a successful sell.
    get_global_var
        Return a value from the shared key store.
    set_global_var
        Save a value to the shared key store.
    get_strategy
        Load and instantiate a custom strategy from a file.
    """

    def __init__(
        self,
        name: str,
        type: StrategyType,
        batch_id: str,
        schedule: List[Dict],
        ref_run_id: int = None,
        data_loader: DataLoader = None,
        fractional: bool = False,
    ):
        """Initialize the strategy.

        Every subclass must call this initializer.

        Parameters
        ----------
        name: str
            The strategy name, as used in the tradeplan.toml file.
        type: StrategyType
            The strategy type, day trade or swing.
        batch_id: str
            The identifier, generated by the framework, that groups executions.
        schedule: List[Dict]
            The mandatory execution windows from the trade plan; there may be
            several, and the framework does not enforce them.
        ref_run_id: int, default None
            The reference run identifier, used in backtesting.
        data_loader: DataLoader, default None
            The loader, passed by the framework and used like a DataFrame to
            access symbol data.
        fractional: bool, default False
            Whether to support fractional trading.
        """
        self.name = name
        self.batch_id = batch_id
        self.type = type
        self.ref_run_id = ref_run_id
        self.algo_run = AlgoRun(strategy_name=self.name, batch_id=batch_id)
        self.schedule = schedule
        self.data_loader = data_loader
        self.support_fractional = fractional
        self.account_id = None
        self.global_var: Dict = {}

    def __repr__(self):
        """Return the name of the strategy."""
        return self.name

    async def calc_qty(
        self, price: float, trade_fee_percentage: float
    ) -> float:
        """Return the quantity that the account balance can buy at a price.

        Parameters
        ----------
        price: float
            The price per unit.
        trade_fee_percentage: float
            The trade fee, as a fraction of the price.

        Returns
        -------
        Return a fractional quantity if the strategy supports fractional
        trading, and a whole number otherwise.

        Raises
        ------
        Raise AssertionError if account_id is not set.
        """
        if not self.account_id:
            raise AssertionError("account_id not set")
        cash = await Accounts.get_balance(self.account_id)
        price *= 1.0 + trade_fee_percentage
        return cash / price if self.support_fractional else cash // price

    async def create(self) -> bool:
        """Save the strategy run and return whether the strategy should run.

        The framework runs this method upon instantiation, and overrides must
        call the base implementation.

        Returns
        -------
        Return False to keep the framework from executing the strategy, for
        example to run a single copy across several processes.
        """
        await self.algo_run.save(
            pool=config.db_conn_pool, ref_algo_run_id=self.ref_run_id
        )
        return True

    async def should_run_all(self):
        """Return whether the framework should use run_all instead of run.

        The base implementation returns False.
        """
        return False

    async def run_all(
        self,
        symbols_position: Dict[str, float],
        data_loader: DataLoader,
        now: datetime,
        portfolio_value: float = None,
        trader: Trader = None,
        debug: bool = False,
        backtesting: bool = False,
        fee_buy_percentage: float = 0.0,
        fee_sell_percentage: float = 0.0,
    ) -> Dict[str, Dict]:
        """Return trading actions for all symbols at once.

        The framework runs this method periodically, once rather than per
        symbol, when should_run_all returns True.

        Parameters
        ----------
        symbols_position: Dict[str, float]
            The open position quantity per symbol.
        data_loader: DataLoader
            The loader, passed by the framework and used like a DataFrame to
            access symbol data.
        now: datetime
            The current time, which is in the past when backtesting.
        portfolio_value: float, default None
            The portfolio value; to be deprecated.
        trader: Trader, default None
            The trader, passed by the framework; to be deprecated.
        debug: bool, default False
            The debug flag, used mostly in backtesting.
        backtesting: bool, default False
            Whether the call is part of a backtesting session rather than
            real-time trading.
        fee_buy_percentage: float, default 0.0
            The buy fee percentage, from 0 to 1.
        fee_sell_percentage: float, default 0.0
            The sell fee percentage, from 0 to 1.

        Returns
        -------
        Return a dictionary that maps each symbol to its action; see the
        documentation for the supported actions.
        """
        return {}

    async def run(
        self,
        symbol: str,
        shortable: bool,
        position: float,
        now: datetime,
        minute_history: df,
        portfolio_value: float = None,
        debug: bool = False,
        backtesting: bool = False,
    ) -> Tuple[bool, Dict]:
        """Return the trading action for a single symbol.

        The framework runs this method for each symbol when should_run_all
        returns False.

        Parameters
        ----------
        symbol: str
            The symbol to act on.
        shortable: bool
            Whether the symbol may be shorted; to be deprecated.
        position: float
            The current position, which may be 0.
        now: datetime
            The current time with its time zone, which is in the past when
            backtesting.
        minute_history: df
            The DataFrame that holds the symbol's price data.
        portfolio_value: float, default None
            The portfolio value; to be deprecated.
        debug: bool, default False
            The debug flag, used mostly in backtesting.
        backtesting: bool, default False
            Whether the call is part of a backtesting session rather than
            real-time trading.

        Returns
        -------
        Return (False, {}) to take no action, or True and an action; see the
        documentation for the supported actions.
        """
        return False, {}

    async def is_sell_time(self, now: datetime):
        """Return whether the strategy may sell at the given time.

        The base implementation always returns True.

        Parameters
        ----------
        now: datetime
            The time to check.
        """
        return True

    async def is_buy_time(self, now: datetime):
        """Return whether the strategy may buy at the given time.

        The base implementation always returns True.

        Parameters
        ----------
        now: datetime
            The time to check.
        """
        return True

    async def buy_callback(
        self,
        symbol: str,
        price: float,
        qty: float,
        now: datetime = None,
        trade_fee: float = 0.0,
    ) -> None:
        """Handle a successful, possibly partial, buy.

        The framework runs this method after the order executes. The base
        implementation does nothing.

        Parameters
        ----------
        symbol: str
            The symbol bought.
        price: float
            The execution price.
        qty: float
            The quantity bought.
        now: datetime, default None
            The time of the buy.
        trade_fee: float, default 0.0
            The fee charged for the trade.
        """

    async def sell_callback(
        self,
        symbol: str,
        price: float,
        qty: float,
        now: datetime = None,
        trade_fee: float = 0.0,
    ) -> None:
        """Handle a successful, possibly partial, sell.

        The framework runs this method after the order executes. The base
        implementation does nothing.

        Parameters
        ----------
        symbol: str
            The symbol sold.
        price: float
            The execution price.
        qty: float
            The quantity sold.
        now: datetime, default None
            The time of the sell.
        trade_fee: float, default 0.0
            The fee charged for the trade.
        """

    async def get_global_var(self, key):
        """Return the value stored under a key in the shared key store.

        Parameters
        ----------
        key
            The key to look up.

        Returns
        -------
        Return the cached value if this strategy has read or set the key
        before.
        """
        if key in self.global_var:
            return self.global_var[key]

        self.global_var[key] = (val := await KeyStore.load(key))
        return val

    async def set_global_var(self, key, value):
        """Save a value under a key in the shared key store.

        Parameters
        ----------
        key
            The key to store the value under.
        value
            The value to store.
        """
        self.global_var[key] = value
        await KeyStore.save(key, value)

    @classmethod
    async def get_strategy(
        cls,
        batch_id: str,
        strategy_name: str,
        strategy_details: Dict,
        data_loader: DataLoader = None,
        ref_run_id: Optional[int] = None,
    ):
        """Load and instantiate a custom strategy class from a Python file.

        For use by the framework.

        Parameters
        ----------
        batch_id: str
            The batch identifier passed to the new strategy.
        strategy_name: str
            The name of the class to instantiate.
        strategy_details: Dict
            The settings passed to the new strategy, including the source file
            path under "filename"; modified in place.
        data_loader: DataLoader, default None
            The loader passed to the new strategy.
        ref_run_id: Optional[int], default None
            The reference run identifier, used in backtesting.

        Returns
        -------
        Return the new strategy, or None if its create method returns False.

        Raises
        ------
        Raise FileNotFoundError if the file does not exist, and exit the
        process on any other error, including a class that does not inherit
        from Strategy.
        """
        try:
            spec = importlib.util.spec_from_file_location(  # type: ignore
                "module.name", strategy_details["filename"]
            )
            custom_strategy_module = importlib.util.module_from_spec(spec)  # type: ignore
            spec.loader.exec_module(custom_strategy_module)  # type: ignore
            class_name = strategy_name

            custom_strategy = getattr(custom_strategy_module, class_name)

            if not issubclass(custom_strategy, Strategy):
                tlog(f"strategy must inherit from class {Strategy.__name__}")
                exit(0)
            strategy_details.pop("filename", None)
            s = custom_strategy(
                batch_id=batch_id,
                ref_run_id=ref_run_id,
                data_loader=data_loader,
                **strategy_details,
            )
            success = await s.create()
        except FileNotFoundError as e:
            tlog(
                f"[EXCEPTION] {e} : file not found `{strategy_details['filename']}`"
            )
            raise
        except Exception as e:
            tlog(
                f"[Error]exception of type {type(e).__name__} with args {e.args}"
            )
            traceback.print_exc()
            exit(0)
        else:
            return s if success else None
